services:
  user:
    image: monster/user:s1
    container_name: user-services
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - monster-net
    
  ticket:
    image: monster/ticket:s1
    container_name: ticket-services
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - monster-net

networks:
  monster-net:
    driver: bridge
