spring:
  application:
    name: user

  data:
    mongodb:
      uri: mongodb://localhost:27017/foxsec
      auto-index-creation: true

server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
